-- Create a table for products
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a table for orders
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  total_amount numeric not null,
  status text default 'pending',
  items jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert some sample products
insert into products (name, description, price, image_url) values
('Classic Edible Cup (110ml)', 'Perfect for espresso and macchiato. Crunchy vanilla flavor.', 12.99, 'https://jwycwzvkvogeavfdkbab.supabase.co/storage/v1/object/public/images/product.png'),
('Large Edible Cup (220ml)', 'Ideal for cappuccino and latte. Stays crispy for 40 mins.', 15.99, 'https://jwycwzvkvogeavfdkbab.supabase.co/storage/v1/object/public/images/product.png'),
('Chocolate Dipped Cup', 'Lined with premium dark chocolate. A dessert and drink in one.', 18.99, 'https://jwycwzvkvogeavfdkbab.supabase.co/storage/v1/object/public/images/product.png');

-- Set up Row Level Security (RLS)
alter table products enable row level security;
alter table orders enable row level security;

-- Allow anyone to read products
create policy "Public products are viewable by everyone."
  on products for select
  using ( true );

-- Allow users to view their own orders
create policy "Users can view own orders"
  on orders for select
  using ( auth.uid() = user_id );

-- Allow users to insert their own orders
create policy "Users can insert own orders"
  on orders for insert
  with check ( auth.uid() = user_id );
